### ISSUE TITLE
Create group

### ISSUE THREAD

**Issue by hisamafahri** [hisamafahri/cyg#16]
When the user wants to create a group, they can do it by running:

`cyg create group`

It will prompt a group name.

In the config file, it will add:

```toml
# ...

[app.group_name]
files = []
users = []
```
