### ISSUE TITLE
add file to group

### ISSUE THREAD

**Issue by hisamafahri** [hisamafahri/cyg#18]
In the config file, user can run:

`cyg add file`

to add a file to the config file.

Example:

```toml
[group.name]
files = [".env", "src/main.rs"]
users = []
```
